version: '3.8'

services:
  frontend:
    build:
      context: /opt/projects/test-webapp/nextjs-test
      dockerfile: Dockerfile
    image: alessandrocapra/nextjs-test:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8081
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: /opt/projects/test-webapp/backend/Dockerfile.multistage
    image: alessandrocapra/go-test:latest
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    volumes:
      - ./backend/app

volumes:
  backend:
