name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push portfolio Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./portfolio-2024
          push: true
          tags: alessandrocapra/portfolio:latest
          cache-from: type=registry,ref=alessandrocapra/portfolio:latest
          cache-to: type=inline

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull alessandrocapra/portfolio:latest
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d \
              --name portfolio \
              --restart unless-stopped \
              -p 3000:80 \
              -v /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro \
              alessandrocapra/portfolio:latest
