name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./nextjs-test
          push: true
          tags: alessandrocapra/nextjs-test:latest

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker-gs-ping
          file: ./docker-gs-ping/Dockerfile.multistage
          push: true
          tags: alessandrocapra/go-backend:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /path/to/your/project
            docker-compose pull
            docker-compose up -d --force-recreate
